module.exports = [
  '(C) Copyright 2000, 2001, 2002',
  '"Copyright 2011 craigslist, inc."',
  '#     Copyright (C) 1986-1993, 1998, 2004, 2007-2010',
  '# Copyright (C) 2013 Yusuke Suzuki <utatane.tea@gmail.com>',
  '###Copyright (C) 2011 by Charlie McConnell',
  '.\" Copyright (c) 2011, Joyent, Inc.  All Rights Reserved.',
  '.\" Copyright (c) 2011, Robert Mustacchi.  All Rights Reserved.',
  '/* Copyright (C) 1999 Masanao Izumo <iz@onicos.co.jp>',
  '//     Copyright (c) 2010-2012 Robert Kieffer',
  '//     Copyright (c) 2011-2013 John Roepke',
  '// Copyright (c) 2009-2013, Jeff Mott. All rights reserved.',
  '// Copyright (c) 2010 Ryan McGrath',
  '// Copyright (c) 2012 Artur Adib',
  '// Copyright (c) 2012, Mark Cavage. All rights reserved.',
  '// Copyright 2010-2012 Mikeal Rogers',
  '// Copyright 2011 Joyent, Inc.  All rights reserved.',
  '// Copyright 2011 Mark Cavage <mcavage@gmail.com> All rights reserved.',
  '// Copyright 2012 Joyent, Inc.  All rights reserved.',
  '// Portions created by the Initial Developer are Copyright (C) 2007',
  '//=> "Copyright (c) 2014 Jon Schlinkert"',
  '//=> Copyright (c) 2012-2014 Jon Schlinkert',
  '//=> Copyright (c) 2012-2014 Jon Schlinkert.',
  '//=> Copyright (c) 2014 Jon Schlinkert',
  '//=> Copyright (c) 2014 Jon Schlinkert',
  '//=> Copyright (c) 2014 Jon Schlinkert.',
  '//=> Copyright (c) 2014 [Jon Schlinkert](https://github.com/jonschlinkert)',
  '//Copyright Plato http://stackoverflow.com/a/19385911/995876',
  '<a href="http://www.w3.org/Consortium/Legal/copyright-documents-19990405">document',
  '<dc:rights>Copyright 2011 craigslist, inc.</dc:rights>',
  '<p class="copyright"><a href="http://www.w3.org/Consortium/Legal/ipr-notice-20000612#Copyright">Copyright</a>',
  '> Copyright &copy; 2011 Kevin Kwok',
  '> Copyright &copy; 2012 Eli Skeggs',
  '> Copyright &copy; 2013 C. Scott Ananian',
  '@copyright 2011-2013 John Roepke',
  '@license amdefine 0.1.0 Copyright (c) 2011, The Dojo Foundation All Rights Reserved.',
  'Adapted from bzip2.js, copyright 2011 Kevin Kwok (antimatter15@gmail.com).',
  'Adapted from bzip2.js, copyright 2011 antimatter15 (antimatter15@gmail.com).',
  'Adapted from node-bzip, copyright 2012 Eli Skeggs.',
  'Based on Underscore.js 1.5.2, copyright 2009-2013 Jeremy Ashkenas,',
  'Copyright   : Copyright c 2011 by Kimberly Geswein All rights reserved',
  'Copyright (C) 2004 Sam Hocevar <sam@hocevar.net>',
  'Copyright (C) 2011 Ariya Hidayat <ariya.hidayat@gmail.com>',
  'Copyright (C) 2011 Arpad Borsos <arpad.borsos@googlemail.com>',
  'Copyright (C) 2011 Kevin Kwok',
  'Copyright (C) 2011 Yusuke Suzuki <utatane.tea@gmail.com>',
  'Copyright (C) 2011 by Yehuda Katz',
  'Copyright (C) 2011-2012 Ariya Hidayat <ariya.hidayat@gmail.com>',
  'Copyright (C) 2012 Ariya Hidayat <ariya.hidayat@gmail.com>',
  'Copyright (C) 2012 Arpad Borsos <arpad.borsos@googlemail.com>',
  'Copyright (C) 2012 Eli Skeggs',
  'Copyright (C) 2012 John Freeman <jfreeman08@gmail.com>',
  'Copyright (C) 2012 Joost-Wim Boekesteijn <joost-wim@boekesteijn.nl>',
  'Copyright (C) 2012 Kris Kowal <kris.kowal@cixar.com>',
  'Copyright (C) 2012 Mathias Bynens <mathias@qiwi.be>',
  'Copyright (C) 2012 Robert Gust-Bardon <donate@robert.gust-bardon.org>',
  'Copyright (C) 2012 Yusuke Suzuki <utatane.tea@gmail.com>',
  'Copyright (C) 2012 [Yusuke Suzuki](http://github.com/Constellation)',
  'Copyright (C) 2012, 2011 [Ariya Hidayat](http://ariya.ofilabs.com/about)',
  'Copyright (C) 2012-2013 Mathias Bynens <mathias@qiwi.be>',
  'Copyright (C) 2012-2013 Michael Ficarra <escodegen.copyright@michael.ficarra.me>',
  'Copyright (C) 2012-2013 Yusuke Suzuki <utatane.tea@gmail.com>',
  'Copyright (C) 2012-2013 [Yusuke Suzuki](http://github.com/Constellation)',
  'Copyright (C) 2013 Ariya Hidayat <ariya.hidayat@gmail.com>',
  'Copyright (C) 2013 C. Scott Ananian',
  'Copyright (C) 2013 Irakli Gozalishvili <rfobic@gmail.com>',
  'Copyright (C) 2013 Mathias Bynens <mathias@qiwi.be>',
  'Copyright (C) 2013 Thaddee Tyl <thaddee.tyl@gmail.com>',
  'Copyright (C) 2013 Yusuke Suzuki <utatane.tea@gmail.com>',
  'Copyright (C) 2013 [Yusuke Suzuki](http://github.com/Constellation)',
  'Copyright (C) 2014 Yusuke Suzuki <utatane.tea@gmail.com>',
  'Copyright (c)  2010-2012 Robert Kieffer',
  'Copyright (c) 2008 Matsuza',
  'Copyright (c) 2009-2011, Kevin Decker kpdecker@gmail.com',
  'Copyright (c) 2009-2011, Mozilla Foundation and contributors',
  'Copyright (c) 2009-2014 TJ Holowaychuk <tj@vision-media.ca>',
  'Copyright (C) 2009-2015 Typesafe Inc. <http://www.typesafe.com>',
  'Copyright (c) 2010',
  'Copyright (c) 2010 Caolan McMahon',
  'Copyright (c) 2010 Christopher West',
  'Copyright (c) 2010-2012 Robert Kieffer',
  'Copyright (c) 2010-2013 Christian Johansen',
  'Copyright (c) 2010-2014 Christian Johansen',
  'Copyright (c) 2010-2014, Christian Johansen (christian@cjohansen.no) and',
  'Copyright (c) 2010-2014, Christian Johansen, christian@cjohansen.no',
  'Copyright (c) 2011 Christopher West',
  'Copyright (c) 2011 Dominic Tarr',
  'Copyright (c) 2011 Esa-Matti Suuronen esa-matti@suuronen.org',
  'Copyright (c) 2011 Joyent, Inc. and the persons identified as document authors.',
  'Copyright (c) 2011 Matthew Francis',
  'Copyright (c) 2011 Shan Carter',
  'Copyright (c) 2011 Sven Fuchs, Christian Johansen',
  'Copyright (c) 2011 TJ Holowaychuk &lt;tj@vision-media.ca&gt;',
  'Copyright (c) 2011 dreamerslab &lt;ben@dreamerslab.com&gt;',
  'Copyright (c) 2011 hij1nx <http://www.twitter.com/hij1nx>',
  'Copyright (c) 2011-2013 John Roepke',
  'Copyright (c) 2011-2013, Christopher Jeffrey (MIT License).',
  'Copyright (c) 2011-2013, Christopher Jeffrey. (MIT License)',
  'Copyright (c) 2011-2013, Christopher Jeffrey. (MIT Licensed)',
  'Copyright (c) 2011-2014 JP Richardson',
  'Copyright (c) 2012 Another-D-Mention Software and other contributors,',
  'Copyright (c) 2012 Barnesandnoble.com, llc, Donavon West, and Domenic Denicola',
  'Copyright (c) 2012 Mark Cavage',
  'Copyright (c) 2012 Matt Mueller &lt;mattmuelle@gmail.com&gt;',
  'Copyright (c) 2012 Maximilian Antoni',
  'Copyright (c) 2012 Simon Boudrias (twitter: @vaxilart)',
  'Copyright (c) 2012 Simon Boudrias (twitter: [@vaxilart](https://twitter.com/Vaxilart))',
  'Copyright (c) 2012 Tyler Kellen',
  'Copyright (c) 2012 Tyler Kellen. See LICENSE for further details.',
  'Copyright (c) 2012 [Vitaly Puzrin](https://github.com/puzrin).',
  'Copyright (c) 2012, 2013 moutjs team and contributors (http://moutjs.com)',
  'Copyright (c) 2012-2013 Jared Hanson <http://jaredhanson.net/>',
  'Copyright (c) 2012-2013, Eran Hammer <eran@hueniverse.com>',
  'Copyright (c) 2013 "Cowboy" Ben Alman',
  'Copyright (c) 2013 Assemble',
  'Copyright (c) 2013 Brian Woodward',
  'Copyright (c) 2013 C. Scott Ananian',
  'Copyright (c) 2013 Garen J. Torikian',
  'Copyright (c) 2013 Garen Torikian',
  'Copyright (c) 2013 Jared Hanson <[http://jaredhanson.net/](http://jaredhanson.net/)>',
  'Copyright (c) 2013 Jon Schlinkert, Brian Woodward, contributors',
  'Copyright (c) 2013 Jon Schlinkert, contributors.',
  'Copyright (c) 2013 Julian Gruber &lt;julian@juliangruber.com&gt;',
  'Copyright (c) 2013 Kyle Robinson Young',
  'Copyright (c) 2013 Matt Mueller <mattmuelle@gmail.com>',
  'Copyright (c) 2013 Maximilian Antoni',
  'Copyright (c) 2013 Segment.io &lt;friends@segment.io&gt;',
  'Copyright (c) 2013 Simon Boudrias',
  'Copyright (c) 2013 Simon Boudrias (twitter: @vaxilart)',
  'Copyright (c) 2013 Upstage.',
  'Copyright (c) 2013 Viacheslav Lotsmanov',
  'Copyright (c) 2013 [Richardson & Sons, LLC](http://richardsonandsons.com/)',
  'Copyright (c) 2013 [Richardson & Sons, LLC](http://richardsonandsons.com/)\r',
  'Copyright (c) 2013 \"Cowboy\" Ben Alman',
  'Copyright (c) 2013 hij1nx',
  'Copyright (c) 2013, Assemble, contributors',
  'Copyright (c) 2013, Deoxxa Development',
  'Copyright (c) 2013, Dominic Tarr',
  'Copyright (c) 2013, Jon Schlinkert, contributors',
  'Copyright (c) 2013, Jon Schlinkert.',
  'Copyright (c) 2014 "Cowboy" Ben Alman',
  'Copyright (c) 2014 Aron Nopanen',
  'Copyright (c) 2014 Assemble, contributors.',
  'Copyright (c) 2014 Brian Woodward',
  'Copyright (c) 2014 Brian Woodward, Jon Schlinkert, contributors.',
  'Copyright (c) 2014 Brian Woodward, contributors.',
  'Copyright (c) 2014 Charlike Mike Reagent (cli), contributors.',
  'Copyright (c) 2014 Fractal <contact@wearefractal.com>',
  'Copyright (c) 2014 Hugh Kennedy',
  'Copyright (c) 2014 Jon Schlinkert',
  'Copyright (c) 2014 Jon Schlinkert <https://github.com/jonschlinkert>',
  'Copyright (c) 2014 Jon Schlinkert, Brian Woodward',
  'Copyright (c) 2014 Jon Schlinkert, Brian Woodward, contributors',
  'Copyright (c) 2014 Jon Schlinkert, Brian Woodward, contributors.',
  'Copyright (c) 2014 Jon Schlinkert, Brian Woodward.',
  'Copyright (c) 2014 Jon Schlinkert, contributors',
  'Copyright (c) 2014 Jon Schlinkert, contributors.',
  'Copyright (c) 2014 Julian Gruber &lt;julian@juliangruber.com&gt;',
  'Copyright (c) 2014 Matthew Mueller &lt;mattmuelle@gmail.com&gt;',
  'Copyright (c) 2014 Petka Antonov',
  'Copyright (c) 2014 Segment.io Inc. &lt;friends@segment.io&gt;',
  'Copyright (c) 2014 Sellside, Jon Schlinkert and Brian Woodward',
  'Copyright (c) 2014 Simon Boudrias (twitter: @vaxilart)',
  'Copyright (c) 2014 TJ Holowaychuk &lt;tj@vision-media.ca&gt;',
  'Copyright (c) 2014 [Jon Schlinkert](http://twitter.com/jonschlinkert), [Brian Woodward](http://twitter.com/doowb), contributors.',
  'Copyright (c) 2014 [Shinnosuke Watanabe](https://github.com/shinnn)',
  'Copyright (c) 2014 \"Cowboy\" Ben Alman',
  'Copyright (c) 2014 bl contributors',
  'Copyright (c) 2014, Jon Schlinkert, Brian Woodward',
  'Copyright (c) 2014, Jon Schlinkert, Brian Woodward, contributors.',
  'Copyright (c) 2014, Jon Schlinkert, contributors',
  'Copyright (c) 2014, Jon Schlinkert, contributors.',
  'Copyright (c) 2014-2015 Jon Schlinkert, contributors.',
  'Copyright (c) 2015 Jon Schlinkert, contributors.',
  'Copyright (c) Craig Spaeth <craigspaeth@gmail.com>, Art.sy, 2011-2013',
  'Copyright 2009-2011 Mozilla Foundation and contributors',
  'Copyright 2009-2013 Jeremy Ashkenas, DocumentCloud Inc.',
  'Copyright 2009-2013 Jeremy Ashkenas, DocumentCloud and Investigative Reporters & Editors',
  'Copyright 2009-2014 Jeremy Ashkenas, DocumentCloud and Investigative Reporters & Editors',
  'Copyright 2010, 2011, Chris Winberry <chris@winberry.net>. All rights reserved.',
  'Copyright 2010, Chris Winberry <chris@winberry.net>. All rights reserved.',
  'Copyright 2010-2014 Caolan McMahon',
  'Copyright 2011 - Present AJ ONeal',
  'Copyright 2011 Mozilla Foundation and contributors',
  'Copyright 2011 The Closure Compiler Authors. All rights reserved.',
  'Copyright 2011 Twitter, Inc.',
  'Copyright 2011, John Resig',
  'Copyright 2011, The Dojo Foundation',
  'Copyright 2012 (c) Mihai Bazon <mihai.bazon@gmail.com>',
  'Copyright 2012 Michael Hart (michael.hart.au@gmail.com)',
  'Copyright 2012 Mozilla Foundation and contributors',
  'Copyright 2012- GoInstant, Inc. and other contributors. All rights reserved.',
  'Copyright 2012-2013 The Dojo Foundation <http://dojofoundation.org/>',
  'Copyright 2012-2014 The Dojo Foundation <http://dojofoundation.org/>',
  'Copyright 2012-2014, JP Richardson  <jprichardson@gmail.com>',
  'Copyright 2013 Assemble',
  'Copyright 2014 Mozilla Foundation and contributors',
  'Copyright Dustin Diaz 2011',
  'Copyright © 2011-2014 [Paul Vorbach](http://paul.vorba.ch/) and',
  'Copyright © 2013–2014 Domenic Denicola <domenic@domenicdenicola.com>',
  'Copyright(c) 2010 LearnBoost <dev@learnboost.com>',
  'Copyright(c) 2010 TJ Holowaychuk <tj@vision-media.ca>',
  'Copyright(c) 2011 Ben Lin <ben@dreamerslab.com>',
  'Copyright(c) 2011 TJ Holowaychuk <tj@vision-media.ca>',
  'Copyright(c) 2012 Truepattern',
  'Copyright(c) 2014 Jonathan Ong',
  'Originally modified from scrawl.js. Copyright (c) 2014 [Caolan McMahon](https://github.com/caolan), contributors.',
  'Simple BufferStream is Copyright (c) 2012 Rod Vagg [@rvagg](https://twitter.com/rvagg) and licenced under the MIT licence. All rights not explicitly granted in the MIT license are reserved. See the included LICENSE file for more details.',
  'Simple BufferStream is Copyright (c) 2012 Rod Vagg [@rvagg](https://twitter.com/rvagg) and licenced under the MIT licence. All rights not explicitly granted in the MIT license are reserved. See the included LICENSE file for more details.",',
  'Sqwish is copyright Dustin Diaz 2011 under MIT License',
  'bl** is Copyright (c) 2013 Rod Vagg [@rvagg](https://twitter.com/rvagg) and licenced under the MIT licence. All rights not explicitly granted in the MIT license are reserved. See the included LICENSE.md file for more details.',
  'expectedHtml = "<p>Copyright &copy; 2003-2014</p>",',
  'expectedXml = "<p>Copyright &#xA9; 2003-2014</p>",',
  'isStream** is Copyright (c) 2014 Rod Vagg [@rvagg](https://twitter.com/rvagg) and licenced under the MIT licence. All rights not explicitly granted in the MIT license are reserved. See the included LICENSE file for more details.',
  'php.js is copyright 2011 Kevin van Zonneveld.',
  'through2** is Copyright (c) 2013 Rod Vagg [@rvagg](https://twitter.com/rvagg) and licenced under the MIT licence. All rights not explicitly granted in the MIT license are reserved. See the included LICENSE file for more details.',
  'to.js - copyright(c) 2012 openmason.',
  'use</a> and <a href="http://www.w3.org/Consortium/Legal/copyright-software-19980720">software',
  'var str = "<!doctype html><html><head><title>Some test</title></head><body><footer><p>Copyright &copy; 2003-2014</p></footer></body></html>",'
];
